### ISSUE TITLE
Please provide requirements.txt for python3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by denisgolius** [MrFellox/flimsy-timer#1]
```
 python3 app.py 
Utils initialized
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from scripts import settings
  File "/tmp/flimsy-timer/flimsy-timer/scripts/settings.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

As I see it need kivy, tkinter and other libs so it will be nice to add requirements.txt with needed packages and their version to run it on linux or others systems.

**Comment by MrFellox** [comment]
Hey there, sorry for the inconvinient, I forgot the part where you need to install the dependencies when building from source code. I'll add it on the project's root.

**Comment by MrFellox** [comment]
Something isn't right. I don't know how is Tkinter missing if Tkinter comes with Python.
